---
- name: Pull docker image of Scientific_calc
  hosts: all
  tasks:
    - name: Pull Scientific_calc devops image
      docker_image:
        name: ayushimakhija/Scientific_calc
        source: pull